### ISSUE TITLE
Bug: Create EMI compat is broken by this mod.

### ISSUE THREAD

**Issue by rtxyd** [LeadRDRK/umapyoi-fabric#2]
### Describe the bug

sequenced assembling recipe can't be loaded.

```
[01:30:47] [Thread-21/ERROR]: [EMI] java.util.ArrayList.get(ArrayList.java:427)
	at com.simibubi.create.compat.emi.recipes.CreateEmiRecipe.<init>(CreateEmiRecipe.java:59)
	at com.simibubi.create.compat.emi.recipes.basin.BasinEmiRecipe.<init>(BasinEmiRecipe.java:25)
	at com.simibubi.create.compat.emi.recipes.basin.MixingEmiRecipe.<init>(MixingEmiRecipe.java:14)
	at com.simibubi.create.compat.emi.CreateEmiPlugin.addAll(CreateEmiPlugin.java:311)
	at com.simibubi.create.compat.emi.CreateEmiPlugin.register(CreateEmiPlugin.java:250)
	at dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:185)
	at java.base
```

### Steps to reproduce

mod list:
![image](https://github.com/LeadRDRK/umapyoi-fabric/assets/65117312/df0ed365-941c-4748-8edd-d55b685c0344)

start the game and try to look up sequenced assembling recipe in emi.

### Expected behavior

sequenced assembling recipe like "precision mechanism" should be shown.

### Screenshots

[2024-05-22-7.log](https://github.com/LeadRDRK/umapyoi-fabric/files/15393552/2024-05-22-7.log)

### Versions

- OS: windows 10
- Launcher: hmcl
- Java version: Zulu Platform x64 Architecture 17.0.9
- Minecraft version: 1.20.1
- Umapyoi version: 1.1.2

**Comment by rtxyd** [comment]
after remove folder `umapyoi-1.1.2-1.20.1.jar\data\umapyoi\recipes\integration\create` it can be correctly loaded.

**Comment by rtxyd** [comment]
I think I find the reason, forge format in fabric mod.
https://github.com/LeadRDRK/umapyoi-fabric/blob/7c9f9f35364ee2a201215207481d69a5954be21c/src/main/resources/data/umapyoi/recipes/integration/create/mixing/sweetcupcake_from_mixing.json#L4

**Comment by LeadRDRK** [comment]
I didn't pay much attention to the Create integrations while making this port, so they haven't been worked on at all since the beginning. I'll fix it later when I have time, or you can do a pull request if you wanna fix it yourself.
