### ISSUE TITLE
Bug: java.lang.IndexOutOfBoundsException: readerIndex(8) + length(8) exceeds writerIndex(8

### ISSUE THREAD

**Issue by 0999312** [LeadRDRK/umapyoi-fabric#4]
### Describe the bug

Could not open GUI in Training Terminal & Three Goddess
Logs have Error executing task on Client

### Steps to reproduce

Trying to open Training Terminal & Three Goddess 's GUI

### Expected behavior

GUI should be opened

### Screenshots

```
[23:02:13] [Render thread/ERROR]: Error executing task on Client
java.lang.IndexOutOfBoundsException: readerIndex(8) + length(8) exceeds writerIndex(8): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 8, widx: 8, cap: 256)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.97.Final.jar:?]
	at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:835) ~[netty-buffer-4.1.97.Final.jar:?]
	at net.minecraft.class_2540.readLong(class_2540.java:1338) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10811(class_2540.java:428) ~[client-intermediary.jar:?]
	at net.tracen.umapyoi.container.ThreeGoddessContainer.getTileEntity(ThreeGoddessContainer.java:104) ~[%5B       %5D%20umapyoi-1.1.2-1.20.4.jar:?]
	at net.tracen.umapyoi.container.ThreeGoddessContainer.<init>(ThreeGoddessContainer.java:27) ~[%5B       %5D%20umapyoi-1.1.2-1.20.4.jar:?]
	at net.fabricmc.fabric.api.screenhandler.v1.ExtendedScreenHandlerType.create(ExtendedScreenHandlerType.java:96) ~[fabric-screen-handler-api-v1-1.3+78d798af4f-7c934b735e60ae3c.jar:?]
	at net.tracen.umapyoi.network.OpenScreenPacket.handler(OpenScreenPacket.java:76) ~[%5B       %5D%20umapyoi-1.1.2-1.20.4.jar:?]
	at net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking.lambda$wrapTyped$1(ClientPlayNetworking.java:391) ~[fabric-networking-api-v1-3.1.8+2e5ac5484f-74f1ace5a6935f0d.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[QLS       ϰ .jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) ~[?:?]

```

### Versions

- OS: 
- Launcher: 
- Java version: 
- Minecraft version: 1.20.4
- Umapyoi version: 1.1.2-1.20.4

### Additional context

[logs.zip](https://github.com/user-attachments/files/15823516/logs.zip)

**Comment by LeadRDRK** [comment]
Note: Fix not confirmed because I cannot reproduce the issue (please reopen if it still happens)
